# application.yml 是 springboot 框架的配置文件
# spring 框架会默认的去 resources 下寻找名为 application.yml的配置文件

server:
  port: 8083

# 数据源配置
spring:
  application:
    name: bm-user-service
  cloud:
    nacos:
      discovery:
        # 配置nacos服务器的地址
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        # 不写默认是public  命名空间用于将不同的服务划分为不同的组 标记不同的生产环境
        namespace: public
  datasource:
    # 数据库标准链接, 数据库类型  jdbc效率最高，但是麻烦, 所以咱们用mybatis-plus
    url: jdbc:mysql://localhost:3306/bm-user
    type: com.alibaba.druid.pool.DruidDataSource
    # 账号密码
    username: root
    password: 123456
